threading: Use modern GCC atomic builtins for __GNUC__
The __sync builtins have been deprecated and replaced since GCC 4.7
with the more flexible __atomic builtins. While the __sync builtins
continue to work, they lack the 64-bit version __sync_fetch_and_add_8()
which causes x265 failing to build on certain 32-bit Linux targets
such as m68k, powerpc or sh4:

/usr/bin/powerpc-linux-gnu-ld.bfd: libx265.so.216: undefined reference to `__sync_fetch_and_add_8'
collect2: error: ld returned 1 exit status

Switching over to the new __atomic builtins in GCC fixes this problem.